export const types = {
  GET_RESTAURANTS: 'GET_RESTAURANTS',
  LOADING: 'LOADING',
  SEARCH_RESTAURANT: 'SEARCH_RESTAURANT',
  SEARCH_RESTAURANT_NAME: 'SEARCH_RESTAURANT_NAME',
  RESTAURANT_ERROR: 'RESTAURANT_ERROR',
};
